# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expire_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
